use_frameworks!

platform :ios, '9.0'

target 'ct-sheet-ios_Example' do
  pod 'ct-sheet-ios', :path => '../'

  target 'ct-sheet-ios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
